Connection reset by 140.82.116.4 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
rftime('%Y-%m-%d')
  File "/home/fishtrap/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 6296, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/fishtrap/.local/lib/python3.10/site-packages/pandas/core/accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/fishtrap/.local/lib/python3.10/site-packages/pandas/core/indexes/accessors.py", line 643, in __new__
    raise AttributeError("Can only use .dt accessor with datetimelike values")
AttributeError: Can only use .dt accessor with datetimelike values. Did you mean: 'at'?
